name: Build
run-name: Building project

on: workflow_dispatch


jobs:
  build_and_test:
    name: Rust project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target-dir build_output/
      
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qtextract build
          path: build_output